In [ ]:
A = {"a": 0.2, "b": 0.3, "c": 0.6, "d": 0.6}
B = {"a": 0.9, "b": 0.9, "c": 0.4, "d": 0.5}

Y = {}

for key in A:
    Y[key] = max(A[key], B[key])

print('Fuzzy Set Union is:', Y)


Fuzzy Set Union is : {'a': 0.9, 'b': 0.9, 'c': 0.6, 'd': 0.6}


In [ ]:
A = {"a": 0.2, "b": 0.3, "c": 0.6, "d": 0.6}
B = {"a": 0.9, "b": 0.9, "c": 0.4, "d": 0.5}

Y = {}

for key in A:
    Y[key] = min(A[key], B[key])

print('Fuzzy Set Intersection is:', Y)


Fuzzy Set Intersection is : {'a': 0.2, 'b': 0.3, 'c': 0.4, 'd': 0.5}


In [ ]:
#COMPLEMENT
for A_key in A:
    Y[A_key]= 1-A[A_key]
         
print('Fuzzy Set Complement is :', Y)

Fuzzy Set Complement is : {'a': 0.8, 'b': 0.7, 'c': 0.4, 'd': 0.4}


In [ ]:
A = {"a": 0.2, "b": 0.3, "c": 0.6, "d": 0.6}
B = {"a": 0.9, "b": 0.9, "c": 0.4, "d": 0.5}

Y = {}

for key in A:
    B_complement = 1 - B[key]  
    Y[key] = min(A[key], B_complement)  

print('Fuzzy Set Difference is:', Y)



Fuzzy Set Difference is : {'a': 0.09999999999999998, 'b': 0.09999999999999998, 'c': 0.6, 'd': 0.5}


In [ ]:
A = {"a": 0.2, "b": 0.3, "c": 0.6, "d": 0.6}
B = {"x": 0.9, "y": 0.9, "z": 0.4}

cartesian_product = {}

for key_A in A:
    for key_B in B:
        cartesian_product[(key_A, key_B)] = min(A[key_A], B[key_B])

print('Fuzzy Set Cartesian Product is:', cartesian_product)


Cartesian product: [[0.2 0.2 0.2 0.2]
 [0.3 0.3 0.3 0.3]
 [0.6 0.6 0.4 0.5]
 [0.6 0.6 0.4 0.5]]


In [2]:
#MAX MIN COMPOSITION

import numpy as np

def max_min_composition(R1, R2):
    result = np.zeros((len(R1), len(R2[0])))
    for i in range(len(R1)):
        for j in range(len(R2[0])):
            max_min = 0
            for k in range(len(R1[0])):
                max_min = max(min(R1[i][k], R2[k][j]), max_min)
            result[i][j] = max_min
    
    result = np.clip(result, 0, 1)
    return result


R1 = np.array([[0.3, 0.4, 0.7], [0.3, 0.5, 0], [0.4, 0.4, 1]])
R2 = np.array([[0.3, 0.3, 0], [0.3, 0.5, 0.1], [0.4, 0.4, 0]])
result = max_min_composition(R1, R2)
print("Max-Min Composition Result:")
print(result)

Max-Min Composition Result:
[[0.4 0.4 0.1]
 [0.3 0.5 0.1]
 [0.4 0.4 0.1]]


In [1]:
# Define fuzzy relations R (A → B) and S (B → C)
R = {
    "a": {"x": 0.7, "y": 0.5},
    "b": {"x": 0.4, "y": 0.9}
}

S = {
    "x": {"p": 0.8, "q": 0.6},
    "y": {"p": 0.5, "q": 0.7}
}

# Compute Min-Max Composition
result = {}

for a in R:  # Iterate over rows of R
    result[a] = {}
    for c in S["x"]:  # Iterate over columns of S
        result[a][c] = max(min(R[a][b], S[b][c]) for b in R[a])

# Print result
print("Min-Max Composition:", result)


Min-Max Composition: {'a': {'p': 0.7, 'q': 0.6}, 'b': {'p': 0.5, 'q': 0.7}}
